name: Java CI with Gradle

# Trigger workflow on any push or pull request
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      # Cache Gradle packages for faster builds
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Grant execute permission to Gradle wrapper inside subfolder
      - name: Grant execute permission for gradlew
        run: chmod +x AlgorithmVisualizer/gradlew

      # Build the project from subfolder
      - name: Build with Gradle
        run: ./AlgorithmVisualizer/gradlew build --stacktrace

      # Run tests from subfolder
      - name: Run tests
        run: ./AlgorithmVisualizer/gradlew test --stacktrace
